steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID'
      - '.'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID'

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID'
      - '--region'
      - '$_REGION'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,RAPIDAPI_KEY=RAPIDAPI_KEY:latest'
      - '--allow-unauthenticated'

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'asia-northeast3' # Default region (Seoul), can be overridden
  _REPO_NAME: 'native-thinking-repo'
  _SERVICE_NAME: 'native-thinking-app'
  _VITE_FIREBASE_API_KEY: 'AIzaSyC00l8tiA2YppntCbSPFDKaVZcrGTDmhb4'
  _VITE_FIREBASE_AUTH_DOMAIN: 'native-thinking.firebaseapp.com'
  _VITE_FIREBASE_PROJECT_ID: 'native-thinking'
  _VITE_FIREBASE_STORAGE_BUCKET: 'native-thinking.firebasestorage.app'
  _VITE_FIREBASE_MESSAGING_SENDER_ID: '991798310970'
  _VITE_FIREBASE_APP_ID: '1:991798310970:web:a01b97f2c1cbb2b6e21d03'
